[build]
  command   = "npm run build"
  publish   = "dist"

# Redirige todas las rutas al index.html para que Vue Router funcione correctamente (SPA)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
